services:
  backend:
    build:
      context: C:\Users\devpl\AppData\Local\Temp\volume-compose-dev-env-gallant_hamilton\backend
      dockerfile: C:\Users\devpl\AppData\Local\Temp\volume-compose-dev-env-gallant_hamilton\backend\Dockerfile
      target: development
    command:
    - infinity
    depends_on:
      db:
        condition: service_started
    entrypoint:
    - sleep
    init: true
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: compose-dev-env-gallant_hamilton
    networks:
      default: null
    secrets:
    - source: db-password
    volumes:
    - type: volume
      source: volume-compose-dev-env-gallant_hamilton
      target: /com.docker.devenvironments.code
    - type: volume
      source: vsCodeServerVolume-compose-dev-env-gallant_hamilton-backend
      target: /home/vscode
  db:
    command:
    - infinity
    entrypoint:
    - sleep
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    expose:
    - "3306"
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
      - -h
      - 127.0.0.1
      - --silent
      interval: 3s
      retries: 5
      start_period: 30s
    image: mariadb
    init: true
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: compose-dev-env-gallant_hamilton
    networks:
      default: null
    restart: always
    secrets:
    - source: db-password
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
      volume: {}
    - type: volume
      source: volume-compose-dev-env-gallant_hamilton
      target: /com.docker.devenvironments.code
    - type: volume
      source: vsCodeServerVolume-compose-dev-env-gallant_hamilton-db
      target: /home/vscode
  proxy:
    build:
      context: C:\Users\devpl\AppData\Local\Temp\volume-compose-dev-env-gallant_hamilton\proxy
      dockerfile: C:\Users\devpl\AppData\Local\Temp\volume-compose-dev-env-gallant_hamilton\proxy\Dockerfile
    command:
    - infinity
    depends_on:
      backend:
        condition: service_started
    entrypoint:
    - sleep
    init: true
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: compose-dev-env-gallant_hamilton
    networks:
      default: null
    ports:
    - mode: ingress
      target: 80
      published: 8080
      protocol: tcp
    volumes:
    - type: volume
      source: volume-compose-dev-env-gallant_hamilton
      target: /com.docker.devenvironments.code
    - type: volume
      source: vsCodeServerVolume-compose-dev-env-gallant_hamilton-proxy
      target: /home/vscode
networks:
  default:
    name: compose-dev-env-gallant_hamilton_default
volumes:
  db-data:
    name: compose-dev-env-gallant_hamilton_db-data
  volume-compose-dev-env-gallant_hamilton:
    name: volume-compose-dev-env-gallant_hamilton
  vsCodeServerVolume-compose-dev-env-gallant_hamilton-backend:
    name: vsCodeServerVolume-compose-dev-env-gallant_hamilton-backend
  vsCodeServerVolume-compose-dev-env-gallant_hamilton-db:
    name: vsCodeServerVolume-compose-dev-env-gallant_hamilton-db
  vsCodeServerVolume-compose-dev-env-gallant_hamilton-proxy:
    name: vsCodeServerVolume-compose-dev-env-gallant_hamilton-proxy
secrets:
  db-password:
    name: compose-dev-env-gallant_hamilton_db-password
    file: C:\Users\devpl\AppData\Local\Temp\volume-compose-dev-env-gallant_hamilton\db\password.txt
